name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/brocolito-setup
      - run: bro changed_files
        id: find-changed-files
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: echo ${{ steps.find-changed-files.outputs.changed_files }}
